import type { DocumentExecutionContext, DocumentResult, DocumentFormat, DocumentQaReport } from "./types";
import * as fs from "fs";
import * as path from "path";
import { runVisualQA } from "./qaVisualPipeline";
import { getPalette } from "./designSystem";

const ARTIFACTS_DIR = path.join(process.cwd(), "artifacts");

function ensureArtifactsDir(): void {
  if (!fs.existsSync(ARTIFACTS_DIR)) fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9\u00C0-\u024F _-]/g, "").replace(/\s+/g, "_").slice(0, 60);
}

function extractTitle(msg: string): string {
  const line = msg.split("\n")[0]?.trim() ?? "Document";
  return (line.length > 80 ? line.slice(0, 80) : line) || "Untitled";
}

function extractSections(msg: string): string[] {
  const lines = msg.split("\n").filter(l => l.trim().length > 0);
  return lines.length <= 1 ? ["Introduction", "Content"] : lines.slice(1, 4).map(l => l.trim());
}

const MIME: Record<string, string> = {
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pdf: "application/pdf",
};

function saveArtifact(buf: Buffer, name: string): string {
  ensureArtifactsDir();
  const stored = `${Date.now()}_${sanitize(name)}`;
  fs.writeFileSync(path.join(ARTIFACTS_DIR, stored), buf);
  return stored;
}

function toResult(
  buf: Buffer, filename: string, fmt: DocumentFormat,
  ctx: DocumentExecutionContext, qa: DocumentQaReport, ms: number,
): DocumentResult {
  const stored = saveArtifact(buf, filename);
  console.log(`[SkillExecutor] ${fmt}: ${stored} (${buf.length} bytes)`);
  return {
    buffer: buf, filename,
    mimeType: MIME[fmt] ?? "application/octet-stream",
    downloadUrl: `/api/artifacts/${stored}/download`,
    metadata: {
      skillId: `${fmt}-create`, operation: ctx.operation,
      backendUsed: ctx.backend, paletteId: ctx.palette, durationMs: ms, qa,
    },
  };
}

function failQa(fmt: string, err: unknown, ms: number): DocumentQaReport {
  return {
    status: "failed", severity: "high",
    findings: [`${fmt.toUpperCase()} generation error: ${err instanceof Error ? err.message : String(err)}`],
    metrics: { validationMs: ms, repairLoops: 0 },
  };
}

// -- PPTX -------------------------------------------------------------------

export async function executePptx(ctx: DocumentExecutionContext): Promise<DocumentResult> {
  const t = Date.now();
  try {
    const { generatePptx } = await import("../../services/documentGenerators/pptxGenerator");
    const title = extractTitle(ctx.userMessage);
    const sections = extractSections(ctx.userMessage);
    const content = {
      title, subtitle: "Generated by IliaGPT", author: "IliaGPT",
      slides: sections.map((text, i) => ({
        type: "content" as const,
        title: i === 0 ? "Overview" : `Section ${i + 1}`,
        bullets: [text],
      })),
    };
    const r = await generatePptx(content);
    const qa = await runVisualQA(r.buffer, "pptx");
    return toResult(r.buffer, r.filename, "pptx", ctx, qa, Date.now() - t);
  } catch (err) {
    return toResult(Buffer.alloc(0), "error.pptx", "pptx", ctx, failQa("pptx", err, Date.now() - t), Date.now() - t);
  }
}

// -- DOCX -------------------------------------------------------------------

export async function executeDocx(ctx: DocumentExecutionContext): Promise<DocumentResult> {
  const t = Date.now();
  try {
    const { generateWord } = await import("../../services/documentGenerators/wordGenerator");
    const title = extractTitle(ctx.userMessage);
    const content = {
      title, author: "IliaGPT",
      sections: extractSections(ctx.userMessage).map((text, i) => ({
        heading: i === 0 ? "Introduction" : `Section ${i + 1}`,
        paragraphs: [text],
      })),
    };
    const r = await generateWord(content);
    const qa = await runVisualQA(r.buffer, "docx");
    return toResult(r.buffer, r.filename, "docx", ctx, qa, Date.now() - t);
  } catch (err) {
    return toResult(Buffer.alloc(0), "error.docx", "docx", ctx, failQa("docx", err, Date.now() - t), Date.now() - t);
  }
}

// -- XLSX -------------------------------------------------------------------

export async function executeXlsx(ctx: DocumentExecutionContext): Promise<DocumentResult> {
  const t = Date.now();
  try {
    const { generateExcel } = await import("../../services/documentGenerators/excelGenerator");
    const title = extractTitle(ctx.userMessage);
    const headers = extractSections(ctx.userMessage).slice(0, 5);
    const h = headers.length > 0 ? headers : ["Column A", "Column B", "Column C"];
    const content = {
      sheetName: "Data", title, headers: h,
      rows: [h.map((_, i) => `Sample ${i + 1}`), h.map((_, i) => `Data ${i + 1}`)],
    };
    const r = await generateExcel(content);
    const qa = await runVisualQA(r.buffer, "xlsx");
    return toResult(r.buffer, r.filename, "xlsx", ctx, qa, Date.now() - t);
  } catch (err) {
    return toResult(Buffer.alloc(0), "error.xlsx", "xlsx", ctx, failQa("xlsx", err, Date.now() - t), Date.now() - t);
  }
}

// -- PDF --------------------------------------------------------------------

export async function executePdf(ctx: DocumentExecutionContext): Promise<DocumentResult> {
  const t = Date.now();
  try {
    const { generatePdf } = await import("../../services/documentGenerators/pdfGenerator");
    const title = extractTitle(ctx.userMessage);
    const content = {
      title, author: "IliaGPT",
      sections: extractSections(ctx.userMessage).map((text, i) => ({
        heading: i === 0 ? "Introduction" : `Section ${i + 1}`,
        paragraphs: [text],
      })),
    };
    const r = await generatePdf(content);
    const qa = await runVisualQA(r.buffer, "pdf");
    return toResult(r.buffer, r.filename, "pdf", ctx, qa, Date.now() - t);
  } catch (err) {
    return toResult(Buffer.alloc(0), "error.pdf", "pdf", ctx, failQa("pdf", err, Date.now() - t), Date.now() - t);
  }
}
