export const COUNTRIES = [
    { code: '+54', name: 'Argentina', flag: '🇦🇷' },
    { code: '+591', name: 'Bolivia', flag: '🇧🇴' },
    { code: '+55', name: 'Brasil', flag: '🇧🇷' },
    { code: '+56', name: 'Chile', flag: '🇨🇱' },
    { code: '+57', name: 'Colombia', flag: '🇨🇴' },
    { code: '+506', name: 'Costa Rica', flag: '🇨🇷' },
    { code: '+53', name: 'Cuba', flag: '🇨🇺' },
    { code: '+593', name: 'Ecuador', flag: '🇪🇨' },
    { code: '+503', name: 'El Salvador', flag: '🇸🇻' },
    { code: '+34', name: 'España', flag: '🇪🇸' },
    { code: '+1', name: 'Estados Unidos/Canadá', flag: '🇺🇸' },
    { code: '+502', name: 'Guatemala', flag: '🇬🇹' },
    { code: '+504', name: 'Honduras', flag: '🇭🇳' },
    { code: '+52', name: 'México', flag: '🇲🇽' },
    { code: '+505', name: 'Nicaragua', flag: '🇳🇮' },
    { code: '+507', name: 'Panamá', flag: '🇵🇦' },
    { code: '+595', name: 'Paraguay', flag: '🇵🇾' },
    { code: '+51', name: 'Perú', flag: '🇵🇪' },
    { code: '+1', name: 'Puerto Rico', flag: '🇵🇷' },
    { code: '+1', name: 'República Dominicana', flag: '🇩🇴' },
    { code: '+598', name: 'Uruguay', flag: '🇺🇾' },
    { code: '+58', name: 'Venezuela', flag: '🇻🇪' },
    // Europe & Others
    { code: '+49', name: 'Alemania', flag: '🇩🇪' },
    { code: '+599', name: 'Antillas Holandesas', flag: '🇨🇼' },
    { code: '+213', name: 'Argelia', flag: '🇩🇿' },
    { code: '+61', name: 'Australia', flag: '🇦🇺' },
    { code: '+43', name: 'Austria', flag: '🇦🇹' },
    { code: '+32', name: 'Bélgica', flag: '🇧🇪' },
    { code: '+501', name: 'Belice', flag: '🇧🇿' },
    { code: '+86', name: 'China', flag: '🇨🇳' },
    { code: '+82', name: 'Corea del Sur', flag: '🇰🇷' },
    { code: '+45', name: 'Dinamarca', flag: '🇩🇰' },
    { code: '+20', name: 'Egipto', flag: '🇪🇬' },
    { code: '+971', name: 'Emiratos Árabes', flag: '🇦🇪' },
    { code: '+33', name: 'Francia', flag: '🇫🇷' },
    { code: '+44', name: 'Reino Unido', flag: '🇬🇧' },
    { code: '+30', name: 'Grecia', flag: '🇬🇷' },
    { code: '+509', name: 'Haití', flag: '🇭🇹' },
    { code: '+91', name: 'India', flag: '🇮🇳' },
    { code: '+62', name: 'Indonesia', flag: '🇮🇩' },
    { code: '+353', name: 'Irlanda', flag: '🇮🇪' },
    { code: '+972', name: 'Israel', flag: '🇮🇱' },
    { code: '+39', name: 'Italia', flag: '🇮🇹' },
    { code: '+1', name: 'Jamaica', flag: '🇯🇲' },
    { code: '+81', name: 'Japón', flag: '🇯🇵' },
    { code: '+212', name: 'Marruecos', flag: '🇲🇦' },
    { code: '+47', name: 'Noruega', flag: '🇳🇴' },
    { code: '+31', name: 'Países Bajos', flag: '🇳🇱' },
    { code: '+351', name: 'Portugal', flag: '🇵🇹' },
    { code: '+7', name: 'Rusia', flag: '🇷🇺' },
    { code: '+46', name: 'Suecia', flag: '🇸🇪' },
    { code: '+41', name: 'Suiza', flag: '🇨🇭' },
    { code: '+66', name: 'Tailandia', flag: '🇹🇭' },
    { code: '+90', name: 'Turquía', flag: '🇹🇷' },
    { code: '+380', name: 'Ucrania', flag: '🇺🇦' },
].sort((a, b) => a.name.localeCompare(b.name));
