import React, { useEffect, useState, useRef } from "react";
import mermaid from "mermaid";
import DOMPurify from "dompurify";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Loader2, Play, CheckCircle2, Circle, AlertCircle, RefreshCw } from "lucide-react";
import { cn } from "@/lib/utils";
import { apiFetch } from "@/lib/apiClient";
import { SimulatorErrorBoundary } from "./SimulatorErrorBoundary";

interface Task {
    id: string;
    name: string;
    type: string;
    description: string;
    status: 'pending' | 'ready' | 'executing' | 'completed' | 'failed' | 'cancelled';
    priority: number;
    estimatedDuration: number;
    cost: number;
    dependencies: string[];
    subtasks?: Task[];
    toolName?: string;
    toolParams?: Record<string, any>;
    result?: any;
    error?: string;
    // UI state driven fields
    enabled?: boolean;
}

interface Plan {
    id: string;
    goal: string;
    status: string;
    tasks: Task[];
    metadata: {
        totalCost: number;
        estimatedDuration: number;
        completedTasks: number;
        failedTasks: number;
        progressPercent: number;
    };
    mermaidDiagram: string;
}

interface PlanViewerProps {
    planId?: string;
    className?: string;
    autoRefresh?: boolean;
}

export function PlanViewer({ planId, className, autoRefresh = true }: PlanViewerProps) {
    const [plan, setPlan] = useState<Plan | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const mermaidRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        mermaid.initialize({
            startOnLoad: false,
            theme: 'neutral',
            securityLevel: 'loose',
            fontFamily: 'inherit',
        });
    }, []);

    const toggleTask = async (taskId: string, currentEnabled: boolean) => {
        if (!planId) return;
        // Optimistic update locally? For now, simple await
        try {
            const res = await apiFetch(`/api/planning/plans/${planId}/step`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    taskId,
                    updates: { enabled: !currentEnabled }
                })
            });
            if (res.ok) {
                fetchPlan(); // Refresh full plan to reflect logic changes
            }
        } catch (e) {
            console.error("Failed to toggle task", e);
        }
    };

    const fetchPlan = async () => {
        if (!planId) return;

        try {
            setLoading(true);
            const res = await apiFetch(`/api/planning/plans/${planId}`);
            if (!res.ok) throw new Error("Failed to fetch plan");

            const data = await res.json();
            if (data.success) {
                setPlan(data.plan);
                setError(null);
            } else {
                setError(data.error);
            }
        } catch (err) {
            setError((err as Error).message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchPlan();

        if (autoRefresh && planId) {
            const interval = setInterval(fetchPlan, 2000); // Poll every 2s
            return () => clearInterval(interval);
        }
    }, [planId, autoRefresh]);

    useEffect(() => {
        if (plan?.mermaidDiagram && mermaidRef.current) {
            // IMPROVEMENT #7: Live Execution Highlighting
            // Inject class definitions into the diagram source before rendering
            let diagram = plan.mermaidDiagram;

            // Add custom class styles
            diagram += `
            classDef active fill:#3b82f620,stroke:#3b82f6,stroke-width:2px;
            classDef completed fill:#22c55e20,stroke:#22c55e,stroke-width:2px;
            classDef failed fill:#ef444420,stroke:#ef4444,stroke-width:2px;
            `;

            // Append classes to nodes based on task status
            // Note: This matches the node IDs generated by HTNPlanner (e.g. T1, T2) 
            // We need to ensure HTNPlanner output uses IDs that match tasks. Assuming simple mapping for now.
            // If the mermaid diagram uses task.id as node id:
            plan.tasks.forEach(task => {
                if (task.status === 'executing') diagram += `\nclass ${task.id} active;`;
                else if (task.status === 'completed') diagram += `\nclass ${task.id} completed;`;
                else if (task.status === 'failed') diagram += `\nclass ${task.id} failed;`;
            });

            // IMPROVEMENT #5: Sanitize Labels (simple regex replace to avoid script injections in labels)
            diagram = diagram.replace(/["<>&]/g, (c) => {
                switch (c) {
                    case '<': return '&lt;';
                    case '>': return '&gt;';
                    case '"': return '&quot;';
                    case '&': return '&amp;';
                    default: return c;
                }
            });

            mermaid.render(`mermaid-${plan.id}`, diagram).then((renderResult) => {
                if (mermaidRef.current) {
                    // FRONTEND FIX #1: Sanitize SVG output from Mermaid to prevent XSS
                    const sanitizedSvg = DOMPurify.sanitize(renderResult.svg, {
                        USE_PROFILES: { svg: true, svgFilters: true },
                        ADD_TAGS: ['use'],
                    });
                    mermaidRef.current.innerHTML = sanitizedSvg;
                }
            });
        }
    }, [plan, plan?.mermaidDiagram, plan?.id, plan?.tasks]);

    if (!planId) return null;

    if (loading && !plan) {
        return (
            <Card className={cn("w-full h-full flex items-center justify-center min-h-[200px]", className)}>
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </Card>
        );
    }

    if (error) {
        return (
            <Card className={cn("w-full border-red-200", className)}>
                <CardContent className="pt-6 text-red-500 flex items-center gap-2">
                    <AlertCircle className="h-5 w-5" />
                    <span>Error loading plan: {error}</span>
                </CardContent>
            </Card>
        );
    }

    if (!plan) return null;

    return (
        <SimulatorErrorBoundary>
            <Card className={cn("flex flex-col h-full", className)}>
                <CardHeader className="pb-4">
                    <div className="flex items-center justify-between">
                        <div className="space-y-1">
                            <CardTitle className="text-lg flex items-center gap-2">
                                <span className="truncate max-w-[300px]">{plan.goal}</span>
                                <StatusBadge status={plan.status} />
                            </CardTitle>
                            <CardDescription>
                                {plan.metadata.completedTasks} / {plan.tasks.length} tasks •
                                Est. {(plan.metadata.estimatedDuration / 1000 / 60).toFixed(1)}m •
                                Cost: {plan.metadata.totalCost} tokens
                            </CardDescription>
                        </div>
                        <Button variant="outline" size="icon" onClick={fetchPlan} disabled={loading}>
                            <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} />
                        </Button>
                    </div>

                    {/* Progress Bar */}
                    <div className="h-2 w-full bg-secondary rounded-full overflow-hidden mt-2">
                        <div
                            className="h-full bg-primary transition-all duration-500 ease-out"
                            style={{ width: `${plan.metadata.progressPercent}%` }}
                        />
                    </div>
                </CardHeader>

                <div className="flex-1 overflow-hidden grid grid-cols-1 md:grid-cols-2 gap-4 p-4 pt-0">
                    {/* Graph View */}
                    <Card className="overflow-hidden border-border/50 bg-secondary/10">
                        <div ref={mermaidRef} className="w-full h-full flex items-center justify-center p-4 min-h-[300px] [&>svg]:max-w-full [&>svg]:h-auto" />
                    </Card>

                    {/* List View */}
                    <ScrollArea className="h-full max-h-[500px] pr-4">
                        <div className="space-y-3">
                            {plan.tasks.map((task) => (
                                <TaskItem
                                    key={task.id}
                                    task={task}
                                    onToggle={() => toggleTask(task.id, task.enabled !== false)}
                                    readOnly={plan.status !== 'pending' && plan.status !== 'planning' && plan.status !== 'ready'}
                                />
                            ))}
                        </div>
                    </ScrollArea>
                </div>

                {(plan?.status === 'ready' || plan?.status === 'planning') && (
                    <div className="p-4 border-t bg-muted/20 flex justify-end">
                        <Button
                            onClick={async () => {
                                if (!plan) return;
                                try {
                                    const res = await apiFetch(`/api/planning/plans/${plan.id}/execute`, { method: 'POST' });
                                    if (res.ok) {
                                        fetchPlan();
                                    }
                                } catch (e) {
                                    console.error("Failed to execute plan", e);
                                }
                            }}
                            className="gap-2"
                        >
                            <Play className="w-4 h-4" />
                            Ejecutar Plan
                        </Button>
                    </div>
                )}
            </Card>
        </SimulatorErrorBoundary>
    );
}

function TaskItem({ task, onToggle, readOnly }: { task: Task; onToggle: () => void; readOnly: boolean }) {
    const icon = getStatusIcon(task.status);
    const isEnabled = task.enabled !== false; // Default true

    return (
        <div className={cn(
            "p-3 rounded-lg border text-sm transition-all",
            !isEnabled ? "opacity-50 bg-muted dashed border-dashed" :
                task.status === 'executing' ? "border-primary bg-primary/5 shadow-sm" :
                    task.status === 'completed' ? "border-green-200 bg-green-50/50 dark:bg-green-900/10 dark:border-green-800" :
                        task.status === 'failed' ? "border-red-200 bg-red-50/50 dark:bg-red-900/10 dark:border-red-800" :
                            "border-border bg-card"
        )}>
            <div className="flex items-start gap-3">
                <div
                    className={cn("mt-0.5 cursor-pointer", readOnly && "cursor-default")}
                    onClick={!readOnly ? onToggle : undefined}
                    title={readOnly ? "Read only" : "Click to toggle task"}
                >
                    {isEnabled ? icon : <Circle className="h-4 w-4 text-muted-foreground" />}
                </div>
                <div className="flex-1 space-y-1">
                    <div className="flex items-center justify-between">
                        <span className={cn("font-medium", !isEnabled && "line-through")}>{task.name}</span>
                        <div className="flex items-center gap-2">
                            {task.priority > 0 && <Badge variant="secondary" className="text-[10px] h-5 px-1.5">P{task.priority}</Badge>}
                            <Badge variant="outline" className="text-[10px] h-5 px-1.5 uppercase font-normal opacity-70">
                                {task.type}
                            </Badge>
                        </div>
                    </div>
                    <p className="text-muted-foreground text-xs">{task.description}</p>

                    {task.status === 'executing' && (
                        <div className="flex items-center gap-2 text-primary text-xs animate-pulse">
                            <Loader2 className="h-3 w-3 animate-spin" />
                            Executing {task.toolName ? `using ${task.toolName}` : '...'}
                        </div>
                    )}

                    {task.error && (
                        <div className="text-red-500 text-xs mt-1 bg-red-100/50 dark:bg-red-900/20 p-1.5 rounded">
                            Error: {task.error}
                        </div>
                    )}

                    {task.subtasks && task.subtasks.length > 0 && (
                        <Accordion type="single" collapsible className="w-full">
                            <AccordionItem value="subtasks" className="border-none">
                                <AccordionTrigger className="py-1 text-xs text-muted-foreground hover:no-underline">
                                    {task.subtasks.length} subtasks
                                </AccordionTrigger>
                                <AccordionContent>
                                    <div className="pl-4 space-y-2 mt-2 border-l-2 border-border/50">
                                        {task.subtasks.map(st => (
                                            <TaskItem key={st.id} task={st} onToggle={() => { }} readOnly={true} />
                                        ))}
                                    </div>
                                </AccordionContent>
                            </AccordionItem>
                        </Accordion>
                    )}
                </div>
            </div>
        </div>
    );
}

function StatusBadge({ status }: { status: string }) {
    const variants: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
        completed: "default", // Success usually green, using default for now
        executing: "default",
        failed: "destructive",
        pending: "outline",
        ready: "secondary",
        cancelled: "secondary",
    };

    return (
        <Badge variant={variants[status] || "outline"} className={cn(
            status === 'completed' && "bg-green-500 hover:bg-green-600 border-transparent",
            status === 'executing' && "bg-blue-500 hover:bg-blue-600 border-transparent animate-pulse"
        )}>
            {status}
        </Badge>
    );
}

function getStatusIcon(status: string) {
    switch (status) {
        case 'completed': return <CheckCircle2 className="h-4 w-4 text-green-500" />;
        case 'failed': return <AlertCircle className="h-4 w-4 text-red-500" />;
        case 'executing': return <Loader2 className="h-4 w-4 text-blue-500 animate-spin" />;
        case 'pending': return <Circle className="h-4 w-4 text-muted-foreground/40" />;
        case 'ready': return <Play className="h-4 w-4 text-orange-400" />;
        default: return <Circle className="h-4 w-4 text-muted-foreground/20" />;
    }
}
