export type FluidFunctionalSkill = {
  name: string;
  description: string;
  instructions: string;
  category: "documents" | "data" | "integrations" | "custom";
  features: string[];
  triggers: string[];
};

// 20 capacidades funcionales listas para importar en lote.
export const FLUID_FUNCTIONAL_SKILLS: FluidFunctionalSkill[] = [
  {
    name: "aws-cli",
    description: "Operaciones AWS: inventario rápido, diagnóstico y acciones seguras por servicio.",
    instructions: "Usa AWS CLI para listar recursos, validar estado y ejecutar cambios no destructivos por defecto. Pide confirmación antes de acciones irreversibles.",
    category: "integrations",
    features: ["inventory", "cost-quickcheck", "iam-safety", "ec2-rds-s3"],
    triggers: ["aws", "ec2", "s3", "rds"],
  },
  {
    name: "docker-ops",
    description: "Gestión fluida de contenedores, imágenes, logs y healthchecks.",
    instructions: "Gestiona Docker con enfoque de continuidad: status, logs, restart selectivo, limpieza segura y reporte de impacto.",
    category: "integrations",
    features: ["container-health", "logs-tail", "image-prune-safe", "compose-support"],
    triggers: ["docker", "compose", "container", "imagen"],
  },
  {
    name: "jira-manager",
    description: "Crear, actualizar y priorizar issues en Jira con contexto técnico.",
    instructions: "Crea y actualiza tickets Jira incluyendo resumen, criterios de aceptación y próximos pasos claros.",
    category: "integrations",
    features: ["issue-create", "workflow-update", "priority-triage", "jql-search"],
    triggers: ["jira", "ticket", "issue", "backlog"],
  },
  {
    name: "linear-sync",
    description: "Sincronización de tareas y proyectos de Linear con estado operativo.",
    instructions: "Sincroniza issues/proyectos de Linear y resume deltas (nuevos, bloqueados, en progreso, cerrados).",
    category: "integrations",
    features: ["delta-sync", "project-rollup", "status-map", "assignee-view"],
    triggers: ["linear", "sync", "project", "roadmap"],
  },
  {
    name: "vercel-deploy",
    description: "Despliegues Vercel con validación de build y smoke checks.",
    instructions: "Dispara deploys, monitorea estado, captura logs clave y reporta URL, commit y resultado de smoke test.",
    category: "integrations",
    features: ["deploy-trigger", "build-watch", "preview-url", "rollback-hint"],
    triggers: ["vercel", "deploy", "preview", "prod"],
  },
  {
    name: "figma-pull",
    description: "Extracción de tokens y assets de Figma para handoff rápido.",
    instructions: "Obtén tokens/activos desde Figma, normaliza nombres y genera salida utilizable por frontend.",
    category: "documents",
    features: ["design-tokens", "asset-export", "naming-normalize", "handoff-notes"],
    triggers: ["figma", "tokens", "design", "ui"],
  },
  {
    name: "gitlab-ops",
    description: "Pipelines, tags y merge requests en GitLab con trazabilidad.",
    instructions: "Administra pipelines GitLab, identifica fallos, y propone/ejecuta acciones de recuperación seguras.",
    category: "integrations",
    features: ["pipeline-status", "mr-review", "tag-release", "runner-debug"],
    triggers: ["gitlab", "pipeline", "mr", "ci"],
  },
  {
    name: "sentry-alert",
    description: "Consulta y triage de errores en Sentry con priorización accionable.",
    instructions: "Analiza incidencias Sentry, agrupa por impacto y sugiere remediación priorizada.",
    category: "data",
    features: ["issue-triage", "regression-detect", "release-correlation", "owner-routing"],
    triggers: ["sentry", "error", "crash", "exception"],
  },
  {
    name: "datadog-metric",
    description: "Métricas de Datadog para salud de servicio y alertas operativas.",
    instructions: "Consulta métricas Datadog, identifica anomalías y resume SLO/latencia/errores con contexto temporal.",
    category: "data",
    features: ["timeseries", "slo-check", "anomaly-scan", "latency-budget"],
    triggers: ["datadog", "metric", "slo", "latency"],
  },
  {
    name: "pagerduty-oncall",
    description: "Incidentes y on-call en PagerDuty con contexto y escalamiento.",
    instructions: "Gestiona incidentes PagerDuty, asignaciones y handoff con estado claro de mitigación.",
    category: "integrations",
    features: ["incident-ack", "escalation-view", "oncall-roster", "handoff-summary"],
    triggers: ["pagerduty", "incident", "oncall", "alert"],
  },
  {
    name: "stripe-dash",
    description: "Visión operativa de pagos, suscripciones y balance en Stripe.",
    instructions: "Consulta pagos/subscripciones Stripe y entrega resumen financiero operativo y anomalías.",
    category: "data",
    features: ["revenue-snapshot", "failed-payment", "subscription-health", "refund-trace"],
    triggers: ["stripe", "payment", "subscription", "billing"],
  },
  {
    name: "twilio-sms",
    description: "Mensajería SMS transaccional con seguimiento de entrega.",
    instructions: "Envía/consulta SMS por Twilio con foco en estado de entrega y reintentos controlados.",
    category: "integrations",
    features: ["sms-send", "delivery-status", "retry-policy", "template-use"],
    triggers: ["twilio", "sms", "otp", "mensaje"],
  },
  {
    name: "sendgrid-mail",
    description: "Correo transaccional con plantillas y métricas básicas.",
    instructions: "Gestiona envíos SendGrid, validando plantilla, destinatarios y estado de envío.",
    category: "integrations",
    features: ["transactional-mail", "template-render", "bounce-check", "send-status"],
    triggers: ["sendgrid", "email", "mail", "transactional"],
  },
  {
    name: "hubspot-crm",
    description: "Operaciones CRM sobre contactos y deals en HubSpot.",
    instructions: "Consulta y actualiza contactos/deals HubSpot con notas claras y siguiente acción recomendada.",
    category: "integrations",
    features: ["contact-lookup", "deal-stage", "activity-log", "next-best-action"],
    triggers: ["hubspot", "crm", "deal", "contact"],
  },
  {
    name: "zendesk-ticket",
    description: "Gestión de tickets Zendesk con clasificación y seguimiento.",
    instructions: "Crea/actualiza tickets Zendesk, clasifica severidad y prepara respuesta sugerida al cliente.",
    category: "integrations",
    features: ["ticket-triage", "priority-routing", "response-draft", "sla-watch"],
    triggers: ["zendesk", "ticket", "support", "sla"],
  },
  {
    name: "google-analytics",
    description: "Lectura de tráfico y comportamiento desde GA4.",
    instructions: "Extrae métricas clave de GA4 y resume insights accionables por periodo y canal.",
    category: "data",
    features: ["traffic-overview", "channel-breakdown", "conversion-read", "period-compare"],
    triggers: ["ga4", "analytics", "traffic", "conversion"],
  },
  {
    name: "supabase-ops",
    description: "Operaciones de tablas, migraciones y funciones edge en Supabase.",
    instructions: "Administra Supabase con enfoque seguro: inspección, migración controlada y verificación posterior.",
    category: "integrations",
    features: ["table-admin", "migration-run", "edge-functions", "policy-check"],
    triggers: ["supabase", "postgres", "migration", "edge"],
  },
  {
    name: "kubernetes-ops",
    description: "Operación de pods/deployments/services en Kubernetes.",
    instructions: "Realiza diagnóstico K8s (pods, logs, eventos) y acciones de recuperación graduales.",
    category: "integrations",
    features: ["pod-health", "rollout-status", "event-diagnosis", "safe-restart"],
    triggers: ["kubernetes", "k8s", "pod", "deployment"],
  },
  {
    name: "terraform-apply",
    description: "Plan y apply de IaC con revisión de impacto.",
    instructions: "Ejecuta Terraform plan/apply con control de cambios y reporte del diff aplicado.",
    category: "integrations",
    features: ["plan-review", "state-check", "apply-guard", "drift-detect"],
    triggers: ["terraform", "iac", "infra", "plan"],
  },
  {
    name: "prometheus-query",
    description: "Consultas PromQL para monitoreo y análisis temporal.",
    instructions: "Ejecuta PromQL y devuelve interpretación operativa de tendencias y umbrales.",
    category: "data",
    features: ["promql-run", "timeseries-compare", "threshold-check", "incident-context"],
    triggers: ["prometheus", "promql", "metrics", "monitoring"],
  },
];
