import { sql } from "drizzle-orm";
import {
  pgTable,
  text,
  varchar,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { users } from "./auth";

// Laptop/Desktop "Nodes" paired to an organization (tenant).
// A node is a remote agent/daemon that can execute jobs (screenshot, fs ops, etc.).
export const nodes = pgTable(
  "nodes",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),

    // Tenant scope (Hola uses orgId as the primary tenancy boundary).
    orgId: text("org_id").notNull().default("default"),

    // Who paired/owns this node (used for audit + initial management).
    ownerUserId: varchar("owner_user_id").notNull().references(() => users.id, { onDelete: "cascade" }),

    name: text("name").notNull(),
    platform: text("platform"), // win|mac|linux
    agentVersion: text("agent_version"),

    // Node-reported capabilities (what it can do) and server policy (what we allow).
    capabilities: jsonb("capabilities").notNull().default(sql`'{}'::jsonb`),
    policy: jsonb("policy").notNull().default(sql`'{}'::jsonb`),

    // Bearer token hash for node authentication (never store the raw token).
    tokenHash: text("token_hash").notNull(),

    lastSeenAt: timestamp("last_seen_at"),
    revokedAt: timestamp("revoked_at"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("nodes_org_idx").on(table.orgId),
    index("nodes_owner_idx").on(table.ownerUserId),
    index("nodes_last_seen_idx").on(table.lastSeenAt),
    uniqueIndex("nodes_org_name_unique").on(table.orgId, table.name),
  ]
);

export type Node = typeof nodes.$inferSelect;
export type InsertNode = typeof nodes.$inferInsert;

// Short-lived pairing codes generated by a logged-in user.
export const nodePairings = pgTable(
  "node_pairings",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: text("org_id").notNull().default("default"),
    createdByUserId: varchar("created_by_user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    code: text("code").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    consumedAt: timestamp("consumed_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("node_pairings_org_idx").on(table.orgId),
    index("node_pairings_expires_idx").on(table.expiresAt),
    uniqueIndex("node_pairings_code_unique").on(table.code),
  ]
);

export type NodePairing = typeof nodePairings.$inferSelect;
export type InsertNodePairing = typeof nodePairings.$inferInsert;

export const nodeJobs = pgTable(
  "node_jobs",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: text("org_id").notNull().default("default"),
    nodeId: varchar("node_id").notNull().references(() => nodes.id, { onDelete: "cascade" }),
    requestedByUserId: varchar("requested_by_user_id").notNull().references(() => users.id, { onDelete: "cascade" }),

    kind: text("kind").notNull(),
    payload: jsonb("payload").notNull().default(sql`'{}'::jsonb`),

    status: text("status").notNull().default("queued"),
    result: jsonb("result"),
    error: text("error"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    startedAt: timestamp("started_at"),
    finishedAt: timestamp("finished_at"),
  },
  (table) => [
    index("node_jobs_org_idx").on(table.orgId),
    index("node_jobs_node_idx").on(table.nodeId),
    index("node_jobs_status_idx").on(table.status),
    index("node_jobs_created_idx").on(table.createdAt),
  ]
);

export type NodeJob = typeof nodeJobs.$inferSelect;
export type InsertNodeJob = typeof nodeJobs.$inferInsert;
