import { useState, useCallback, useMemo, memo, useEffect, useRef } from "react";
import { X, ChevronLeft, ChevronRight, Copy, Play, Code, Table, FileImage, GitBranch, FileText, Check, Loader2, FileType } from "lucide-react";
import { cn } from "@/lib/utils";
import { useArtifactStore, type Artifact } from "@/stores/artifactStore";
import { useShikiHighlight } from "@/hooks/useShikiHighlight";
import DOMPurify from "dompurify";

// ============================================
// ARTIFACT TYPE HELPERS
// ============================================

type ArtifactDisplayType = Artifact["type"];

const artifactTypeIcon: Record<ArtifactDisplayType, typeof Code> = {
  code: Code,
  html: FileImage,
  table: Table,
  diagram: GitBranch,
  text: FileText,
  office: FileType,
};

const artifactTypeLabel: Record<ArtifactDisplayType, string> = {
  code: "Code",
  html: "HTML Preview",
  table: "Table",
  diagram: "Diagram",
  text: "Text",
  office: "DOCX",
};

/**
 * Sanitize SVG/HTML content using DOMPurify to prevent XSS.
 * Allows SVG elements and attributes needed for rendering diagrams.
 */
function sanitizeSvg(html: string): string {
  return DOMPurify.sanitize(html, {
    USE_PROFILES: { svg: true, svgFilters: true, html: true },
    ADD_TAGS: ["foreignObject"],
  });
}

// ============================================
// CODE ARTIFACT
// ============================================

const CodeArtifact = memo(function CodeArtifact({ content, language }: { content: string; language?: string }) {
  const [copied, setCopied] = useState(false);
  const lang = language || "text";
  const { html, isLoading } = useShikiHighlight(content, lang);

  const lines = content.split("\n");

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, [content]);

  // Shiki output is trusted (generated by a syntax highlighter library).
  // We sanitize it as an extra precaution.
  const sanitizedHtml = useMemo(() => DOMPurify.sanitize(html), [html]);

  return (
    <div className="relative h-full flex flex-col">
      <div className="absolute top-2 right-2 flex items-center gap-1 z-10">
        <button
          onClick={handleCopy}
          className="p-1.5 rounded-md bg-muted/80 hover:bg-muted transition-colors"
          aria-label={copied ? "Copied" : "Copy code"}
        >
          {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4 text-muted-foreground" />}
        </button>
        <button
          className="p-1.5 rounded-md bg-muted/80 hover:bg-muted transition-colors opacity-50 cursor-not-allowed"
          aria-label="Run code (coming soon)"
          title="Run code (coming soon)"
          disabled
        >
          <Play className="h-4 w-4 text-muted-foreground" />
        </button>
      </div>
      <div className="flex-1 overflow-auto">
        {isLoading ? (
          <div className="flex items-start">
            <div className="select-none pr-4 pl-4 pt-4 text-right text-xs text-muted-foreground/50 font-mono leading-5">
              {lines.map((_, i) => (
                <div key={i}>{i + 1}</div>
              ))}
            </div>
            <pre className="flex-1 p-4 overflow-x-auto">
              <code className="text-sm font-mono">{content}</code>
            </pre>
          </div>
        ) : (
          <div className="flex items-start">
            <div className="select-none pr-4 pl-4 pt-4 text-right text-xs text-muted-foreground/50 font-mono leading-5">
              {lines.map((_, i) => (
                <div key={i}>{i + 1}</div>
              ))}
            </div>
            <div
              className="flex-1 shiki-wrapper [&>pre]:p-4 [&>pre]:m-0 [&>pre]:bg-transparent [&>pre]:overflow-x-auto [&_code]:text-sm [&_code]:font-mono"
              dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
            />
          </div>
        )}
      </div>
    </div>
  );
});

// ============================================
// HTML ARTIFACT
// ============================================

const HtmlArtifact = memo(function HtmlArtifact({ content }: { content: string }) {
  const [showSource, setShowSource] = useState(false);

  const srcDoc = useMemo(() => {
    // Wrap in a full HTML doc if it's just a fragment
    if (/<html[\s>]/i.test(content)) return content;
    return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>body{font-family:system-ui,-apple-system,sans-serif;margin:16px;color:#e4e4e7;background:#09090b;}</style></head>
<body>${content}</body>
</html>`;
  }, [content]);

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center gap-2 px-3 py-1.5 border-b border-border bg-muted/30">
        <button
          onClick={() => setShowSource(false)}
          className={cn(
            "text-xs px-2 py-1 rounded transition-colors",
            !showSource ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"
          )}
        >
          Preview
        </button>
        <button
          onClick={() => setShowSource(true)}
          className={cn(
            "text-xs px-2 py-1 rounded transition-colors",
            showSource ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"
          )}
        >
          Source
        </button>
      </div>
      <div className="flex-1 overflow-hidden">
        {showSource ? (
          <CodeArtifact content={content} language="html" />
        ) : (
          <iframe
            srcDoc={srcDoc}
            sandbox="allow-scripts allow-same-origin"
            className="w-full h-full border-0 bg-white rounded-b-lg"
            title="HTML Preview"
          />
        )}
      </div>
    </div>
  );
});

// ============================================
// TABLE ARTIFACT
// ============================================

const TableArtifact = memo(function TableArtifact({ content }: { content: string }) {
  const [sortColumn, setSortColumn] = useState<string | null>(null);
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");

  const data = useMemo(() => {
    // Try JSON array
    try {
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed)) return parsed;
    } catch {
      // not JSON
    }

    // Try CSV
    const csvLines = content.trim().split("\n");
    if (csvLines.length >= 2 && csvLines[0].includes(",")) {
      const headers = csvLines[0].split(",").map((h) => h.trim().replace(/^"|"$/g, ""));
      return csvLines.slice(1).map((line) => {
        const values = line.split(",").map((v) => v.trim().replace(/^"|"$/g, ""));
        const row: Record<string, string> = {};
        headers.forEach((h, i) => {
          row[h] = values[i] || "";
        });
        return row;
      });
    }

    // Try markdown table
    const mdLines = content.trim().split("\n").filter((l) => l.trim().startsWith("|"));
    if (mdLines.length >= 3) {
      const parseRow = (line: string) =>
        line.split("|").slice(1, -1).map((c) => c.trim());
      const headers = parseRow(mdLines[0]);
      // Skip separator line (mdLines[1])
      return mdLines.slice(2).map((line) => {
        const cells = parseRow(line);
        const row: Record<string, string> = {};
        headers.forEach((h, i) => {
          row[h] = cells[i] || "";
        });
        return row;
      });
    }

    return [];
  }, [content]);

  const columns = useMemo(() => {
    if (data.length === 0) return [];
    return Object.keys(data[0]);
  }, [data]);

  const sortedData = useMemo(() => {
    if (!sortColumn) return data;
    return [...data].sort((a, b) => {
      const aVal = a[sortColumn] ?? "";
      const bVal = b[sortColumn] ?? "";
      const aNum = Number(aVal);
      const bNum = Number(bVal);
      if (!isNaN(aNum) && !isNaN(bNum)) {
        return sortDirection === "asc" ? aNum - bNum : bNum - aNum;
      }
      const cmp = String(aVal).localeCompare(String(bVal));
      return sortDirection === "asc" ? cmp : -cmp;
    });
  }, [data, sortColumn, sortDirection]);

  const handleSort = useCallback(
    (col: string) => {
      if (sortColumn === col) {
        setSortDirection((d) => (d === "asc" ? "desc" : "asc"));
      } else {
        setSortColumn(col);
        setSortDirection("asc");
      }
    },
    [sortColumn]
  );

  if (data.length === 0) {
    return <div className="p-4 text-sm text-muted-foreground">No data to display.</div>;
  }

  return (
    <div className="h-full overflow-auto">
      <table className="w-full text-sm border-collapse">
        <thead className="sticky top-0 bg-muted/80 backdrop-blur-sm z-10">
          <tr>
            {columns.map((col) => (
              <th
                key={col}
                onClick={() => handleSort(col)}
                className="px-3 py-2 text-left font-medium text-muted-foreground cursor-pointer hover:text-foreground transition-colors border-b border-border select-none"
              >
                <span className="flex items-center gap-1">
                  {col}
                  {sortColumn === col && (
                    <span className="text-xs">{sortDirection === "asc" ? "\u25B2" : "\u25BC"}</span>
                  )}
                </span>
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sortedData.map((row, i) => (
            <tr key={i} className="border-b border-border/50 hover:bg-muted/30 transition-colors">
              {columns.map((col) => (
                <td key={col} className="px-3 py-2 text-foreground">
                  {String(row[col] ?? "")}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
});

// ============================================
// DIAGRAM (MERMAID) ARTIFACT
// ============================================

const DiagramArtifact = memo(function DiagramArtifact({ content }: { content: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    async function renderMermaid() {
      try {
        setIsLoading(true);
        setError(null);
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          theme: "dark",
          securityLevel: "loose",
        });
        const id = `mermaid-${Date.now()}`;
        const { svg: renderedSvg } = await mermaid.render(id, content);
        if (!cancelled) {
          // Sanitize the mermaid SVG output
          setSvg(sanitizeSvg(renderedSvg));
          setIsLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to render diagram");
          setIsLoading(false);
        }
      }
    }

    renderMermaid();
    return () => {
      cancelled = true;
    };
  }, [content]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="h-full flex flex-col">
        <div className="px-3 py-2 bg-destructive/10 text-destructive text-xs border-b border-border">
          Diagram error: {error}
        </div>
        <pre className="flex-1 p-4 overflow-auto text-sm font-mono text-muted-foreground">{content}</pre>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className="h-full overflow-auto flex items-center justify-center p-4 [&>svg]:max-w-full"
      dangerouslySetInnerHTML={{ __html: svg || "" }}
    />
  );
});

// ============================================
// TEXT / MARKDOWN ARTIFACT
// ============================================

const TextArtifact = memo(function TextArtifact({ content }: { content: string }) {
  // Lazy-load the markdown renderer to avoid circular deps
  const [RendererModule, setRendererModule] = useState<{
    MarkdownRenderer: React.ComponentType<{ content: string; className?: string }>;
  } | null>(null);

  useEffect(() => {
    import("@/components/markdown-renderer").then((mod) => {
      setRendererModule({ MarkdownRenderer: mod.MarkdownRenderer });
    });
  }, []);

  if (!RendererModule) {
    return (
      <div className="p-4">
        <pre className="text-sm whitespace-pre-wrap">{content}</pre>
      </div>
    );
  }

  return (
    <div className="h-full overflow-auto p-4">
      <RendererModule.MarkdownRenderer content={content} className="prose prose-invert max-w-none" />
    </div>
  );
});

// ============================================
// ARTIFACT BODY RENDERER
// ============================================

const ArtifactBody = memo(function ArtifactBody({ artifact }: { artifact: Artifact }) {
  const version = artifact.versions[artifact.currentVersionIndex];
  if (!version) return null;

  const { content } = version;

  switch (artifact.type) {
    case "code":
      return <CodeArtifact content={content} language={artifact.language} />;
    case "html":
      return <HtmlArtifact content={content} />;
    case "table":
      return <TableArtifact content={content} />;
    case "diagram":
      return <DiagramArtifact content={content} />;
    case "text":
      return <TextArtifact content={content} />;
    default:
      return <CodeArtifact content={content} language="text" />;
  }
});

// ============================================
// MAIN PANEL
// ============================================

export const ArtifactPanel = memo(function ArtifactPanel() {
  const { artifacts, activeArtifactId, isPanelOpen, closePanel, navigateVersion } = useArtifactStore();

  const artifact = activeArtifactId ? artifacts.get(activeArtifactId) : null;

  const [copied, setCopied] = useState(false);

  const handleCopyContent = useCallback(async () => {
    if (!artifact) return;
    const version = artifact.versions[artifact.currentVersionIndex];
    if (!version) return;
    try {
      await navigator.clipboard.writeText(version.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, [artifact]);

  if (!isPanelOpen || !artifact) return null;

  const TypeIcon = artifactTypeIcon[artifact.type];
  const typeLabel = artifactTypeLabel[artifact.type];
  const totalVersions = artifact.versions.length;
  const currentIdx = artifact.currentVersionIndex;
  const hasPrev = currentIdx > 0;
  const hasNext = currentIdx < totalVersions - 1;

  return (
    <>
      {/* Backdrop for mobile */}
      <div
        className="fixed inset-0 bg-black/50 z-40 lg:hidden"
        onClick={closePanel}
      />

      {/* Panel */}
      <div
        className={cn(
          "fixed top-0 right-0 h-full z-50 flex flex-col",
          "bg-background border-l border-border shadow-2xl",
          "w-full md:w-[50vw] xl:w-[45vw]",
          "animate-in slide-in-from-right duration-300"
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-muted/50">
          <div className="flex items-center gap-2 min-w-0">
            <TypeIcon className="h-4 w-4 text-muted-foreground shrink-0" />
            <span className="text-xs text-muted-foreground shrink-0">{typeLabel}</span>
            <span className="text-sm font-medium truncate">{artifact.title}</span>
          </div>
          <div className="flex items-center gap-1 shrink-0">
            {/* Version navigation */}
            {totalVersions > 1 && (
              <div className="flex items-center gap-1 mr-2">
                <button
                  onClick={() => navigateVersion(artifact.id, currentIdx - 1)}
                  disabled={!hasPrev}
                  className="p-1 rounded hover:bg-muted transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                  aria-label="Previous version"
                >
                  <ChevronLeft className="h-4 w-4" />
                </button>
                <span className="text-xs text-muted-foreground whitespace-nowrap">
                  {currentIdx + 1} of {totalVersions}
                </span>
                <button
                  onClick={() => navigateVersion(artifact.id, currentIdx + 1)}
                  disabled={!hasNext}
                  className="p-1 rounded hover:bg-muted transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                  aria-label="Next version"
                >
                  <ChevronRight className="h-4 w-4" />
                </button>
              </div>
            )}
            <button
              onClick={closePanel}
              className="p-2.5 min-w-[44px] min-h-[44px] flex items-center justify-center rounded-md hover:bg-muted transition-colors"
              aria-label="Close panel"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-hidden">
          <ArtifactBody artifact={artifact} />
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-4 py-2 border-t border-border bg-muted/30">
          <div className="text-xs text-muted-foreground">
            {artifact.language && <span className="font-mono">{artifact.language}</span>}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyContent}
              className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs rounded-md bg-muted hover:bg-muted/80 transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied" : "Copy"}
            </button>
          </div>
        </div>
      </div>
    </>
  );
});

export default ArtifactPanel;
