/**
 * PdfEngine — minimal create-from-spec PDF generator using PDFKit.
 *
 * ── Architectural role ──
 *
 * The user-approved architecture designates `pdf-lib` as the primary PDF
 * engine. `pdf-lib` is NOT in the repository today, and the "cero
 * dependencias nuevas" rule agreed to earlier forbids adding it in this
 * slice. `pdfkit@0.17.2` is the in-repo PDF library already used by the
 * PDF generation service — it offers the same create-from-spec surface
 * we need for this engine. When the "no new deps" rule is relaxed, the
 * swap to pdf-lib is a drop-in refactor: both expose a streaming
 * `addPage → text / image → end` API.
 *
 *   Level 0 — PDFKit fresh PDF built from the objective text.
 *   Level 1 — (reserved) pdf-lib template fill (once dep is added).
 *   Level 2 — (reserved) direct PDF stream edit (last resort).
 *
 * Unlike DOCX/XLSX, the Office Engine pipeline for PDF does NOT go
 * through the OOXML ZIP unpack/repack path — PDF is its own format.
 * We still persist the generated bytes through the sandbox + run +
 * artifact registry so the download, preview and metrics contracts
 * stay identical across all doc kinds.
 */

import { createHash, randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { StepStreamer } from "../../../agent/stepStreamer.ts";
import { createSandbox } from "../sandbox.ts";
import { officeWorkerPool } from "../workerPool.ts";
import {
  createRun,
  findIdempotentRun,
  listArtifacts,
  markRunCancelled,
  markRunFailed,
  markRunStarted,
  markRunSucceeded,
  recordArtifact,
  recordStep,
} from "../persistence.ts";
import {
  runStartedCounter,
  runFinishedCounter,
  runDurationHistogram,
  runIdempotentHits,
} from "../metrics.ts";
import type {
  OfficeRunRequest,
  OfficeRunResult,
  OfficeFallbackLevel,
} from "../types.ts";
import { OfficeEngineError } from "../types.ts";

const PDF_MIME = "application/pdf";

export class PdfEngine {
  async run(
    req: OfficeRunRequest,
    streamer: StepStreamer,
    externalSignal?: AbortSignal,
  ): Promise<OfficeRunResult> {
    if (req.docKind !== "pdf") {
      throw new OfficeEngineError(
        "UNSUPPORTED_DOC_KIND",
        `PdfEngine only handles pdf, got ${req.docKind}`,
      );
    }

    // Idempotency (same contract as DOCX/XLSX/PPTX)
    const inputChecksum = req.inputBuffer
      ? createHash("sha256").update(req.inputBuffer).digest("hex")
      : "no-input";
    const objectiveHash = createHash("sha256")
      .update(`${req.docKind}:${req.objective}`)
      .digest("hex");
    const existing = await findIdempotentRun(inputChecksum, objectiveHash, req.docKind);
    if (existing) {
      const cachedArtifacts = await listArtifacts(existing.id);
      const exported = cachedArtifacts.find((a) => a.kind === "exported");
      if (exported && existsSync(exported.path)) {
        runIdempotentHits.inc();
        req.onStart?.(existing.id);
        return {
          runId: existing.id,
          status: "succeeded",
          fallbackLevel: existing.fallbackLevel as OfficeFallbackLevel,
          durationMs: existing.durationMs ?? 0,
          idempotent: true,
          artifacts: cachedArtifacts
            .filter((a) => a.kind === "exported")
            .map((a) => ({
            id: a.id,
            kind: a.kind,
            path: a.path,
            mimeType: a.mimeType,
            sizeBytes: a.sizeBytes,
            checksumSha256: a.checksumSha256,
            downloadUrl: `/api/office-engine/runs/${existing.id}/artifacts/${a.kind}`,
            previewUrl: `/api/office-engine/runs/${existing.id}/artifacts/preview`,
          })),
        };
      }
    }

    const runId = randomUUID();
    const sandbox = await createSandbox(runId);
    const run = await createRun({
      id: runId as unknown as string,
      conversationId: undefined,
      userId: req.userId,
      workspaceId: req.workspaceId ?? undefined,
      objective: req.objective,
      objectiveHash,
      docKind: req.docKind,
      inputChecksum,
      inputName: req.inputName ?? undefined,
      inputSize: req.inputBuffer?.length ?? 0,
      sandboxPath: sandbox.root,
      status: "pending",
      fallbackLevel: 0,
    } as unknown as Parameters<typeof createRun>[0]);

    req.onStart?.(run.id);
    officeWorkerPool.init(); // shares the same pool even though PDF doesn't dispatch OOXML tasks

    const controller = new AbortController();
    if (externalSignal) {
      if (externalSignal.aborted) controller.abort();
      else externalSignal.addEventListener("abort", () => controller.abort(), { once: true });
    }

    const startTs = Date.now();
    runStartedCounter
      .labels(req.docKind, String(req.userId).startsWith("anon_") ? "anon" : "user")
      .inc();
    let seq = 0;
    const stepStart = (stage: string, stepType: string, title: string) => {
      const start = Date.now();
      return async (status: "completed" | "failed", extra?: { diff?: unknown; error?: unknown }) => {
        await recordStep({
          runId: run.id,
          seq: seq++,
          stage,
          stepType,
          title,
          status,
          durationMs: Date.now() - start,
          diff: extra?.diff,
          error: extra?.error,
        });
      };
    };

    try {
      await markRunStarted(run.id);

      // ── Stage 1: plan ──
      const planClose = stepStart("plan", "thinking", "Planificando PDF");
      streamer.start("thinking", "Planificando PDF", { description: req.objective });
      await planClose("completed");

      // ── Stage 2: generate (level 0 — PDFKit fresh) ──
      const genClose = stepStart("edit", "editing", "Generando PDF con PDFKit");
      streamer.start("editing", "Generando PDF con PDFKit (nivel 0)");
      const buffer = await generateFreshPdf(req.objective);
      const checksum = createHash("sha256").update(buffer).digest("hex");
      await genClose("completed", { diff: { added: buffer.length, removed: 0 } });

      // Persist generated → repacked → preview → exported (same artifact
      // chain as DOCX/XLSX/PPTX so the download/preview routes work
      // uniformly across doc kinds).
      const repackedPath = await sandbox.writeBinary("generated.pdf", buffer);
      const repackedArtifact = await recordArtifact({
        runId: run.id,
        kind: "repacked",
        path: repackedPath,
        mimeType: PDF_MIME,
        sizeBytes: buffer.length,
        checksumSha256: checksum,
        versionLabel: "v1",
      });

      // ── Stage 3: preview ──
      const previewClose = stepStart("preview", "generating", "Preparando vista previa pdf");
      streamer.start("generating", "Preparando vista previa PDF");
      const previewPath = await sandbox.writeBinary("preview.pdf", buffer);
      await recordArtifact({
        runId: run.id,
        kind: "preview",
        path: previewPath,
        mimeType: PDF_MIME,
        sizeBytes: buffer.length,
        checksumSha256: checksum,
        versionLabel: "v1",
        parentArtifactId: repackedArtifact.id,
      });
      await previewClose("completed");

      // ── Stage 4: export ──
      const exportClose = stepStart("export", "completed", "Exportando PDF final");
      const outName = (req.inputName?.replace(/\.pdf$/i, "") ?? "document") + ".pdf";
      const exportedPath = await sandbox.writeBinary(outName, buffer);
      const exportRow = await recordArtifact({
        runId: run.id,
        kind: "exported",
        path: exportedPath,
        mimeType: PDF_MIME,
        sizeBytes: buffer.length,
        checksumSha256: checksum,
        versionLabel: "v1",
        parentArtifactId: repackedArtifact.id,
      });
      streamer.add("completed", "Documento listo", {
        output: `PDF listo · ${buffer.length} bytes`,
        artifact: {
          id: "exported",
          name: outName,
          type: "pdf",
          mimeType: PDF_MIME,
          size: buffer.length,
          downloadUrl: `/api/office-engine/runs/${run.id}/artifacts/exported`,
          previewUrl: `/api/office-engine/runs/${run.id}/artifacts/preview`,
        },
      });
      await exportClose("completed");

      const durationMs = Date.now() - startTs;
      const finalLevel: OfficeFallbackLevel = 0;
      await markRunSucceeded(run.id, finalLevel, durationMs);
      runFinishedCounter.labels(req.docKind, "succeeded", String(finalLevel)).inc();
      runDurationHistogram.labels(req.docKind, "succeeded").observe(durationMs / 1000);

      return {
        runId: run.id,
        status: "succeeded",
        fallbackLevel: finalLevel,
        durationMs,
        artifacts: [
          {
            id: exportRow.id,
            kind: "exported",
            path: exportedPath,
            mimeType: PDF_MIME,
            sizeBytes: buffer.length,
            checksumSha256: checksum,
            downloadUrl: `/api/office-engine/runs/${run.id}/artifacts/exported`,
            previewUrl: `/api/office-engine/runs/${run.id}/artifacts/preview`,
          },
        ],
      };
    } catch (err) {
      const durationMs = Date.now() - startTs;
      if (err instanceof OfficeEngineError && err.code === "CANCELLED") {
        await markRunCancelled(run.id, durationMs);
        runFinishedCounter.labels(req.docKind, "cancelled", "0").inc();
        runDurationHistogram.labels(req.docKind, "cancelled").observe(durationMs / 1000);
        return {
          runId: run.id,
          status: "cancelled",
          fallbackLevel: 0,
          durationMs,
          artifacts: [],
          error: { code: "CANCELLED", message: err.message },
        };
      }
      const code = (err instanceof OfficeEngineError ? err.code : "EXPORT_FAILED") as never;
      const message = err instanceof Error ? err.message : String(err);
      await markRunFailed(run.id, code as string, message, durationMs);
      runFinishedCounter.labels(req.docKind, "failed", "0").inc();
      runDurationHistogram.labels(req.docKind, "failed").observe(durationMs / 1000);
      return {
        runId: run.id,
        status: "failed",
        fallbackLevel: 0,
        durationMs,
        artifacts: [],
        error: { code, message },
      };
    }
  }
}

// ---------------------------------------------------------------------------
// PDFKit fresh generation
// ---------------------------------------------------------------------------

async function generateFreshPdf(objective: string): Promise<Buffer> {
  // Dynamic import because pdfkit is a CJS module and we want lazy-loading
  // (so the PdfEngine file can be imported by the engine router without
  // pulling pdfkit into every worker bundle). pdfkit ships no type decls,
  // so we silence the TS7016 at the import site — the narrow API we use
  // (new Document, .on, .fontSize, .text, .end) is stable across 0.x.
  // @ts-expect-error — pdfkit has no bundled type declarations
  const pdfkitModule = await import("pdfkit");
  type PDFDocType = {
    on: (event: "data" | "end" | "error", cb: (...args: unknown[]) => void) => void;
    fontSize: (n: number) => PDFDocType;
    fillColor: (c: string) => PDFDocType;
    text: (s: string, options?: Record<string, unknown>) => PDFDocType;
    moveDown: (n?: number) => PDFDocType;
    end: () => void;
  };
  const PDFDocument = (pdfkitModule as { default: new (options?: Record<string, unknown>) => PDFDocType }).default;
  return new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "LETTER", margin: 72 });
      const chunks: Buffer[] = [];
      doc.on("data", (...args: unknown[]) => {
        chunks.push(args[0] as Buffer);
      });
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (...args: unknown[]) => reject(args[0] as Error));

      doc
        .fontSize(20)
        .fillColor("#0f172a")
        .text(objective.slice(0, 120), { width: 468, align: "left" })
        .moveDown(1)
        .fontSize(12)
        .fillColor("#475569")
        .text("Generado por Office Engine · PDFKit", { width: 468 })
        .moveDown(2)
        .fontSize(14)
        .fillColor("#1e293b")
        .text("Objetivo", { width: 468, underline: true })
        .moveDown(0.5)
        .fontSize(12)
        .fillColor("#334155")
        .text(objective, { width: 468, align: "left" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export const pdfEngine = new PdfEngine();
